# SmartAssetX Backend Configuration
spring.application.name=smartassetx
server.port=8080

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/smartassetxx
spring.datasource.username=postgres
spring.datasource.password=namri
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate Properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Security / JWT properties
# A 256-bit key for HMAC-SHA
smartassetx.jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
smartassetx.jwt.expiration-ms=86400000

# Logging Configurations
logging.level.org.springframework.security=INFO
logging.level.com.smartassetx=DEBUG
